name: Test solution

on:
  push:
    branches: 
    - master
    - develop
  pull_request:
    branches: 
    - master
    - devlop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Restore
      run: dotnet restore
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test
